name: Build and Package with PyInstaller

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.py'
      - '**/requirements.txt'

jobs:
  build-and-package:
    name: Build and Package
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: python-dependencies-${{ hashFiles('**/requirements.txt') }}
        restore-keys: python-dependencies-

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Application
      run: pyinstaller --onefile --windowed --add-data "Favicon.png;." --add-data "cyber_background.png;." --add-data "Bg.PNG;." TUI.py

    - name: Copy NSIS Script
      run: cp installer.nsi ${{ github.workspace }}/installer.nsi

    - name: Check NSIS Installation
      run: |
        $nsisPath = "C:\Program Files (x86)\NSIS\makensis.exe"
        if (-not (Test-Path $nsisPath)) {
          Write-Host "NSIS not found at $nsisPath. Exiting..."
          exit 1
        }

    - name: Compile Installer
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" "${{ github.workspace }}/installer.nsi" -Wait

    - name: Upload Packaged Application
      uses: actions/upload-artifact@v2
      with:
        name: Packaged-App-${{ github.run_id }}
        path: dist/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build-Artifact-${{ github.run_id }}
        path: "${{ github.workspace }}/path/to/your/build/artifact"
