name: Build and Package with PyInstaller

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  PIP_CACHE_DIR: '~/.cache/pip'
  BUILD_DIR: 'dist'
  NSIS_SCRIPT: 'installer.nsi'

jobs:
  build-and-package:
    name: Build and Package
    runs-on: windows-latest
    env:
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      NSIS_PATH: ${{ secrets.NSIS_PATH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: python-dependencies-${{ hashFiles('**/requirements.txt') }}
        restore-keys: python-dependencies-

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --add-data "Favicon.png;." \
          --add-data "cyber_background.png;." \
          --add-data "Bg.PNG;." TUI.py
      working-directory: ${{ github.workspace }}
      shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
      env:
        PYTHON_VERSION: 3.11
        PIP_CACHE_DIR: ~/.cache/pip
        BUILD_DIR: dist
        NSIS_SCRIPT: installer.nsi
        pythonLocation: C:\hostedtoolcache\windows\Python\3.11.7\x64
        OPEN_AI_KEY: ${{ env.OPEN_AI_KEY }}
        NSIS_PATH: ${{ env.NSIS_PATH }}

    - name: Copy NSIS Script
      run: cp .github/workflows/${{ env.NSIS_SCRIPT }} ${{ github.workspace }}/${{ env.NSIS_SCRIPT }}

    - name: Check NSIS Installation
      run: |
        if (-not (Test-Path ${{ env.NSIS_PATH }})) {
          Write-Host "NSIS not found at ${{ env.NSIS_PATH }}. Exiting..."
          exit 1
        }

    - name: Compile Installer
      run: ${{ env.NSIS_PATH }} "${{ github.workspace }}/${{ env.NSIS_SCRIPT }}" -Wait

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Packaged-App-${{ github.run_id }}
        path: ${{ env.BUILD_DIR }}/
